#???
server:
  port: 8080



#?????
spring:
  datasource:
    username: root
    password: 20010720Lmx
    url: jdbc:mysql://47.109.206.82/keaprealClass?&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    # 该属性设为true，就是允许循环引用存在，默认值为false
    allow-circular-references: true

  #????
  transaction:
    rollback-on-commit-failure: true
    default-timeout: 30


  #Redis??
  data:
    redis:
      host: 192.168.201.132
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      database: 0